### ISSUE TITLE
Signalfx can't parse zookeeper AvgLatency metric values

### ISSUE THREAD

**Issue by apratsko** [signalfx/collectd-zookeeper#13]
Since zookeeper 3.6.0, average metric values are set to `double` type: apache/zookeeper#748

Signalfx-agent expects them as `int` and can't parse these values:

Dec 16 12:27:45 ip-10-110-1-50 signalfx-agent: time="2021-12-16T12:27:45Z" level=debug msg="Dispatching value
{plugin: zookeeper; plugin_instance: [zk_version=3.7.0-e3704b390a6697bfdf4b0bef79e3da7a4f6bac4b]; type: gauge; type_instance: zk_avg_latency; host: ; values: ['0.6604']; time: 1639657665.8770773 ; meta: {'0': True}; dsnames: None; dstypes: None; message: None; severity: None}" createdTime=1.6396576658770905e+09 lineno=135 logger=root monitorID=1
2 monitorType=collectd/zookeeper runnerPID=26602 sourcePath=/usr/lib/signalfx-agent/lib/python3.8/site-packages/sfxcollectd/interface.py

Dec 16 12:27:45 ip-10-110-1-50 signalfx-agent: time="2021-12-16T12:27:45Z" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 34 of '0.6604'" monitorID=12 monitorType=collectd/zookeeper runnerPID=26602

**Comment by rmfitzpatrick** [comment]
@apratsko thanks for reporting this issue. This will be resolved in a future agent release: https://github.com/signalfx/collectd-zookeeper/issues/13
